### ISSUE TITLE
Deprecate `.v` for `hcl.scalar`, replace with `.set`

### ISSUE THREAD

**Issue by zzzDavid** [cornell-zhang/hcl-dialect#146]
We are discussing about removing `.v` for `hcl.scalar`. The reason we had `.v` is that we cannot override assignment operation on Python, so we need `.v` as an object property so that we can implement its setter API.

This thread proposes to remove `.v` on the RHS, and replace `.v` with `.set` on the LHS assignment. 
For example:
```python
a = hcl.scalar(10, dtype='int32')
b = hcl.scalar(0, dtype='int32')
b.v = a.v + 1
```
becomes
```python
a = hcl.scalar(10, dtype='int32')
b = hcl.scalar(0, dtype='int32')
b.set(a + 1)
```

**Comment by chhzh123** [comment]
Closed this issue since we no longer have the `.v` construct, and it seems to be a frontend problem.
